on:
  issue_comment:
    types: [created]
jobs:
  OpenAI_Reply:
    if: "contains(github.event.issue.labels.*.name, 'GPT3.5')"
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name: git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install openai
          pip install tiktoken

      - name: Get all issue comments
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p .github
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X GET "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" -o comments.json
          python3 .github/config/ChatGPT.py

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body-file: '.github/comment-template.md'
