on:
  issue_comment:
    types: [created]
jobs:
  OpenAI_Reply:
    if: "contains(github.event.issue.labels.*.name, 'GPT3.5')"
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Get all issue comments
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p .github
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X GET "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" -o comments.json
          python3 ./github/config/ChatGPT.py

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body-file: '.github/comment-template.md'
